### Data Extraction for ACS Data
Uses the clean_acs_data function for each ACS dataset

In [1]:
import sys
import os

# get project root for python script import
project_root = os.path.abspath("..")
sys.path.append(project_root)

from scripts.acs_cleaning import clean_acs_data

In [2]:
import pandas as pd

In [ ]:
# households with no vehicle data
no_vehicle_data = clean_acs_data("1_ACS 2024 Housing Vehicles_8466374152199112599.csv", "% Occupied housing units, no vehicles available, 2024", "no_vehicle_data.csv")
display(no_vehicle_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"% Occupied housing units, no vehicles available, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,15.1
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,1.3
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,0.0
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,1.3
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,7.9
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,0.6
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,2.4
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,2.2
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,4.7
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,1.6

In [5]:
# travel to work data
travel_to_work_data = clean_acs_data("2_ACS 2024 Econ Commuting_8162086740063256068.csv", ["Mean travel time to work (minutes), 2024",
                                                                                           "Mean travel time to work (minutes), 2024",
                                                                                           "# Workers 16 years and over, 2024",
                                                                                           "# Car, truck, or van - carpooled to work, 2024",
                                                                                           "% Car, truck, or van - carpooled to work, 2024",
                                                                                           "# Public transportation to work, 2024",
                                                                                           "% Public transportation to work, 2024",
                                                                                           "# Walked to work, 2024",
                                                                                           "% Walked to work, 2024",],
                                                                                           "travel_to_work_data.csv")
display(travel_to_work_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"Mean travel time to work (minutes), 2024","# Workers 16 years and over, 2024","# Car, truck, or van - carpooled to work, 2024","% Car, truck, or van - carpooled to work, 2024","# Public transportation to work, 2024","% Public transportation to work, 2024","# Walked to work, 2024","% Walked to work, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,31.8,1855,296,16.0,0,0.0,48,2.6
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,30.2,2651,235,8.9,0,0.0,0,0.0
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,28.4,2090,101,4.8,0,0.0,0,0.0
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,36.6,2073,239,11.5,0,0.0,0,0.0
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,31.0,2517,183,7.3,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,33.2,1402,36,2.6,6,0.4,34,2.4
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,33.3,2297,47,2.0,16,0.7,0,0.0
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,34.2,1677,58,3.5,0,0.0,0,0.0
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,34.0,1582,168,10.6,0,0.0,0,0.0
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,34.5,1313,103,7.8,0,0.0,9,0.7

In [6]:
# educational attainment data
educational_attainment_data = clean_acs_data("4_ACS 2024 Social EdAttainment_-6456078396238709508.csv", "% Population 25 years and over, bachelor's degree, 2024", "edu_attainment_data.csv")
display(educational_attainment_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"% Population 25 years and over, bachelor's degree, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,13.7
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,25.7
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,34.0
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,34.1
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,29.3
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,24.6
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,31.9
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,42.5
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,25.6
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,26.1

In [3]:
# unemployment data
unemployment_rate_data = clean_acs_data("6_ACS 2024 Econ Unemployment_2563786966605419871.csv", "% Unemployment Rate, 2024", "unemployment_rate_data.csv")
display(unemployment_rate_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"% Unemployment Rate, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,4.8
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,3.2
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,1.7
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,2.9
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,5.3
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,9.6
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,4.2
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,1.5
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,4.8
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,2.3

In [4]:
# opportunity youth data
opportunity_youth_data = clean_acs_data("7_ACS 2024 Social OppYouth_-8422107928256140074.csv", "% Disconnected youth: ages 16-19 not in school or in labor force, 2024", "opportunity_youth_data.csv")
display(opportunity_youth_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"% Disconnected youth: ages 16-19 not in school or in labor force, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,0.0
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,0.0
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,1.9
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,0.0
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,5.6
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,23.3
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,0.0
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,0.0
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,0.0
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,3.7