### Data Extraction for ACS Data
Uses the clean_acs_data function for each ACS dataset

In [2]:
import sys
import os

# get project root for python script import
project_root = os.path.abspath("..")
sys.path.append(project_root)

from scripts.acs_cleaning import clean_acs_data

In [3]:
import pandas as pd

In [ ]:
# households with no vehicle data
no_vehicle_data = clean_acs_data("1_ACS 2024 Housing Vehicles_8466374152199112599.csv", "% Occupied housing units, no vehicles available, 2024", "no_vehicle_data.csv")
display(no_vehicle_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"% Occupied housing units, no vehicles available, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,15.1
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,1.3
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,0.0
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,1.3
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,7.9
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,0.6
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,2.4
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,2.2
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,4.7
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,1.6

In [5]:
# travel to work data
travel_to_work_data = clean_acs_data("2_ACS 2024 Econ Commuting_8162086740063256068.csv", ["Mean travel time to work (minutes), 2024",
                                                                                           "Mean travel time to work (minutes), 2024",
                                                                                           "# Workers 16 years and over, 2024",
                                                                                           "# Car, truck, or van - carpooled to work, 2024",
                                                                                           "% Car, truck, or van - carpooled to work, 2024",
                                                                                           "# Public transportation to work, 2024",
                                                                                           "% Public transportation to work, 2024",
                                                                                           "# Walked to work, 2024",
                                                                                           "% Walked to work, 2024",],
                                                                                           "travel_to_work_data.csv")
display(travel_to_work_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"Mean travel time to work (minutes), 2024","# Workers 16 years and over, 2024","# Car, truck, or van - carpooled to work, 2024","% Car, truck, or van - carpooled to work, 2024","# Public transportation to work, 2024","% Public transportation to work, 2024","# Walked to work, 2024","% Walked to work, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,31.8,1855,296,16.0,0,0.0,48,2.6
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,30.2,2651,235,8.9,0,0.0,0,0.0
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,28.4,2090,101,4.8,0,0.0,0,0.0
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,36.6,2073,239,11.5,0,0.0,0,0.0
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,31.0,2517,183,7.3,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,33.2,1402,36,2.6,6,0.4,34,2.4
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,33.3,2297,47,2.0,16,0.7,0,0.0
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,34.2,1677,58,3.5,0,0.0,0,0.0
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,34.0,1582,168,10.6,0,0.0,0,0.0
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,34.5,1313,103,7.8,0,0.0,9,0.7

In [6]:
# educational attainment data
educational_attainment_data = clean_acs_data("4_ACS 2024 Social EdAttainment_-6456078396238709508.csv", "% Population 25 years and over, bachelor's degree, 2024", "edu_attainment_data.csv")
display(educational_attainment_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"% Population 25 years and over, bachelor's degree, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,13.7
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,25.7
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,34.0
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,34.1
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,29.3
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,24.6
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,31.9
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,42.5
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,25.6
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,26.1

In [3]:
# unemployment data
unemployment_rate_data = clean_acs_data("6_ACS 2024 Econ Unemployment_2563786966605419871.csv", "% Unemployment Rate, 2024", "unemployment_rate_data.csv")
display(unemployment_rate_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"% Unemployment Rate, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,4.8
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,3.2
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,1.7
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,2.9
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,5.3
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,9.6
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,4.2
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,1.5
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,4.8
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,2.3

In [4]:
# opportunity youth data
opportunity_youth_data = clean_acs_data("7_ACS 2024 Social OppYouth_-8422107928256140074.csv", "% Disconnected youth: ages 16-19 not in school or in labor force, 2024", "opportunity_youth_data.csv")
display(opportunity_youth_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"% Disconnected youth: ages 16-19 not in school or in labor force, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,0.0
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,0.0
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,1.9
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,0.0
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,5.6
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,23.3
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,0.0
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,0.0
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,0.0
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,3.7

In [5]:
# rent burden data
rent_burden_data = clean_acs_data("8_ACS 2024 Housing Affordability_8949469524208423615.csv", "% Gross rent 30.0 percent of income or greater, 2024", "rent_burden_data.csv")
display(rent_burden_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"% Gross rent 30.0 percent of income or greater, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,54.0
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,61.9
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,62.4
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,74.3
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,52.9
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,53.3
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,21.3
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,80.0
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,42.3
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,52.9

In [6]:
# renter occupied data
renter_occupied_data = clean_acs_data("9_ACS 2024 Housing Tenure_-4454289415699796728.csv", "% Renter-occupied housing units, 2024", "renter_occupied_data.csv")
display(renter_occupied_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"% Renter-occupied housing units, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,48.2
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,17.8
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,11.7
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,32.4
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,29.0
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,10.7
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,5.3
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,15.4
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,25.5
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,14.6

In [7]:
# median home value data
median_home_value_data = clean_acs_data("10_ACS 2024 Housing HValue_-2583162591557982240.csv", "Median value of owner-occupied unit (dollars), 2024", "median_home_value_data.csv")
display(median_home_value_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"Median value of owner-occupied unit (dollars), 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,330400.0
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,360600.0
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,530000.0
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,382600.0
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,365300.0
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,322200.0
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,414200.0
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,415400.0
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,398400.0
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,329600.0

In [8]:
# no health insurance data
no_health_ins_data = clean_acs_data("11_ACS 2024 Econ HealthIns_-7160900534032778288.csv", "% Civilian non-institutionalized population, no health insurance, 2024", "no_health_ins_data.csv")
display(no_health_ins_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"% Civilian non-institutionalized population, no health insurance, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,17.8
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,9.2
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,18.0
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,8.6
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,15.3
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,15.7
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,9.5
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,8.6
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,17.1
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,17.0

In [9]:
# preschool enrollment data
preschool_enroll_data = clean_acs_data("12_ACS 2024 Social Enrollment_4807511731336504071.csv", "% Enrolled in nursery school, preschool, 2024", "preschool_enroll_data.csv")
display(preschool_enroll_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"% Enrolled in nursery school, preschool, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,7.3
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,2.2
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,4.0
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,0.0
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,13.1
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,5.0
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,10.0
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,4.9
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,2.3
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,0.0

In [11]:
# adult living alone data
adult_living_alone_data = clean_acs_data("13_ACS 2024 Social HouseholdComp_-815603963663474813.csv", "% Householder 65 years and over living alone, 2024", "adult_living_alone_data.csv")
display(adult_living_alone_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"% Householder 65 years and over living alone, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,26.6
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,14.3
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,9.4
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,12.1
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,15.5
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,7.2
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,6.2
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,2.4
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,13.9
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,9.6

In [12]:
# single parent families data
single_parent_fam_data = clean_acs_data("14_ACS 2024 Social FamilyType_1334278305550881535.csv", "% Single parent families with own children of the householder, 2024", "single_parent_fam_data.csv")
display(single_parent_fam_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"% Single parent families with own children of the householder, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,7.7
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,7.7
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,6.1
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,7.2
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,13.8
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,5.7
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,1.3
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,12.8
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,20.7
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,9.3

In [13]:
# children raised by grandparents data
child_grandparent_data = clean_acs_data("15_ACS 2024 Social Grandparents_-2320451481639583259.csv", "% Children raised by grandparent, 2024", "child_grandparent_data.csv")
display(child_grandparent_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"% Children raised by grandparent, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,0.0
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,0.0
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,5.2
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,22.7
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,0.0
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,4.6
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,0.8
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,4.7
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,5.9
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,0.5

In [14]:
# children under 5 data
under_5_data = clean_acs_data("16_ACS 2024 Demographic SexAge_-709996168819570625.csv", ["# Age under 5 years, 2024", "% Age under 5 years, 2024"], "under_5_data.csv")
display(under_5_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"# Age under 5 years, 2024","% Age under 5 years, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,85,2.3
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,156,3.6
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,342,6.4
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,254,5.4
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,254,5.8
...,...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,156,5.2
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,211,5.4
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,85,2.9
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,188,5.7
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,159,5.3

In [4]:
# child poverty rate
child_poverty_data = clean_acs_data("5_ACS 2024 Econ Poverty_-6377018709685928907.csv", ["# Children for whom poverty status is determined, 2024", "% Children in families below 200 percent of the poverty line, 2024"], "child_poverty_data.csv")
display(child_poverty_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"# Children for whom poverty status is determined, 2024","% Children in families below 200 percent of the poverty line, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,634,39.0
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,893,15.3
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,1700,9.1
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,1562,59.5
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,943,53.6
...,...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,696,22.8
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,660,15.3
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,718,23.7
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,680,28.2
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,715,35.7

In [5]:
# household income data
# DID NOT INCLUDE % households making $100K+
# ADD IF NEEDED
household_income_data = clean_acs_data("18_ACS 2024 Econ Income_8541204371224855650.csv", "Median household income, 2024", "household_income_data.csv")
display(household_income_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"Median household income, 2024"
528,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,63979.0
529,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,105694.0
530,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,118232.0
531,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,109563.0
532,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,105170.0
...,...,...,...,...,...,...,...
709,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,100882.0
710,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,152723.0
711,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,106696.0
712,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,101200.0
713,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,84014.0