### Calculate Modes of Transportation for Commuting to Work Indicator
Based on ACS data for usage of public transportation + walking + carpooling to get to work

In [1]:
import pandas as pd

In [3]:
travel_to_work_data = pd.read_csv("../cleaned_data/travel_to_work_data.csv")
display(travel_to_work_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"Mean travel time to work (minutes), 2024","# Workers 16 years and over, 2024","# Car, truck, or van - carpooled to work, 2024","% Car, truck, or van - carpooled to work, 2024","# Public transportation to work, 2024","% Public transportation to work, 2024","# Walked to work, 2024","% Walked to work, 2024"
0,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,31.8,1855,296,16.0,0,0.0,48,2.6
1,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,30.2,2651,235,8.9,0,0.0,0,0.0
2,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,28.4,2090,101,4.8,0,0.0,0,0.0
3,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,36.6,2073,239,11.5,0,0.0,0,0.0
4,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,31.0,2517,183,7.3,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,33.2,1402,36,2.6,6,0.4,34,2.4
182,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,33.3,2297,47,2.0,16,0.7,0,0.0
183,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,34.2,1677,58,3.5,0,0.0,0,0.0
184,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,34.0,1582,168,10.6,0,0.0,0,0.0
185,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,34.5,1313,103,7.8,0,0.0,9,0.7

In [ ]:
# add up the counts of alternative transportation modes and calculate percentage based on total workers
travel_to_work_data["alt_transport_count"] = (
    travel_to_work_data["# Car, truck, or van - carpooled to work, 2024"] +
    travel_to_work_data["# Public transportation to work, 2024"] +
    travel_to_work_data["# Walked to work, 2024"]
)

travel_to_work_data["alt_transport_pct"] = (
    travel_to_work_data["alt_transport_count"] / travel_to_work_data["# Workers 16 years and over, 2024"] * 100
)

display(travel_to_work_data)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"Mean travel time to work (minutes), 2024","# Workers 16 years and over, 2024","# Car, truck, or van - carpooled to work, 2024","% Car, truck, or van - carpooled to work, 2024","# Public transportation to work, 2024","% Public transportation to work, 2024","# Walked to work, 2024","% Walked to work, 2024",alt_transport_count,alt_transport_pct
0,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,31.8,1855,296,16.0,0,0.0,48,2.6,344,18.544474
1,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,30.2,2651,235,8.9,0,0.0,0,0.0,235,8.864579
2,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,28.4,2090,101,4.8,0,0.0,0,0.0,101,4.832536
3,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,36.6,2073,239,11.5,0,0.0,0,0.0,239,11.529185
4,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,31.0,2517,183,7.3,0,0.0,0,0.0,183,7.270560
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,33.2,1402,36,2.6,6,0.4,34,2.4,76,5.420827
182,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,33.3,2297,47,2.0,16,0.7,0,0.0,63,2.742708
183,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,34.2,1677,58,3.5,0,0.0,0,0.0,58,3.458557
184,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,34.0,1582,168,10.6,0,0.0,0,0.0,168,10.619469
185,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,34.5,1313,103,7.8,0,0.0,9,0.7,112,8.530084

In [10]:
travel_to_work_data = travel_to_work_data.iloc[:, list(range(7)) + [-1]]
display(travel_to_work_data)

travel_to_work_data.to_csv("../cleaned_data/travel_to_work_data_calculated.csv", index=False)

,GEOID,Name of geographic unit,Short Label,Summary level of geographic unit,Geography Vintage,Planning Region,"Mean travel time to work (minutes), 2024",alt_transport_pct
0,13067030104,"Census Tract 301.04, Cobb County",301.04,Tract,2020,Atlanta Regional Commission,31.8,18.544474
1,13067030107,"Census Tract 301.07, Cobb County",301.07,Tract,2020,Atlanta Regional Commission,30.2,8.864579
2,13067030108,"Census Tract 301.08, Cobb County",301.08,Tract,2020,Atlanta Regional Commission,28.4,4.832536
3,13067030109,"Census Tract 301.09, Cobb County",301.09,Tract,2020,Atlanta Regional Commission,36.6,11.529185
4,13067030110,"Census Tract 301.10, Cobb County",301.10,Tract,2020,Atlanta Regional Commission,31.0,7.270560
...,...,...,...,...,...,...,...,...
181,13067031514,"Census Tract 315.14, Cobb County",315.14,Tract,2020,Atlanta Regional Commission,33.2,5.420827
182,13067031515,"Census Tract 315.15, Cobb County",315.15,Tract,2020,Atlanta Regional Commission,33.3,2.742708
183,13067031516,"Census Tract 315.16, Cobb County",315.16,Tract,2020,Atlanta Regional Commission,34.2,3.458557
184,13067031517,"Census Tract 315.17, Cobb County",315.17,Tract,2020,Atlanta Regional Commission,34.0,10.619469
185,13067031518,"Census Tract 315.18, Cobb County",315.18,Tract,2020,Atlanta Regional Commission,34.5,8.530084